name: Sanity Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "sanity"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: build UI
      run: |-
        yarn install
        yarn build --dest ../site
      working-directory: webapp/ui

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make build-backend
