name: Sanity Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "sanity"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: build UI
      run: |-
        yarn install
        yarn build --outDir ../site
      working-directory: webapp/ui

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: lint
      uses: golangci/golangci-lint-action@v3

    - name: ginkgo-lint
      run: |-
        go install github.com/nunnatsa/ginkgolinter/cmd/ginkgolinter@latest
        ginkgolinter ./...

    - name: test
      run: make test

    - name: Build
      run: make build-backend
